<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-15 12:19

$extensionPath = t3lib_extMgm::extPath('taxajax');
return array(
	'tx_taxajax' => $extensionPath . 'class.tx_taxajax.php',
	'tx_taxajax_response' => $extensionPath . 'class.tx_taxajax_response.php',
);
?>